language: generic

sudo : required
services:
  - docker

before_install:
  - docker build -t rbizzell40/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true rbizzell40/docker-react npm run test -- --coverage